### ISSUE TITLE
SLF4j warnings when running with gradle 5.3

### ISSUE THREAD

**Issue by madorb** [spotbugs/spotbugs-gradle-plugin#136] opened 2019-03-29 15:57 UTC
Using gradle `5.3.1` and spotbugs gradle plugin `1.7.1`. Every time i run my build i get the following warnings.

Others have reported this on closed ticket https://github.com/spotbugs/spotbugs/issues/823

```
> Task :web:spotbugsMain
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

> Task :wsclient:spotbugsMain
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by oneiros-de** [comment] 2019-04-02 09:42
Looks like a duplicate of https://github.com/spotbugs/spotbugs-gradle-plugin/issues/133

**Comment by bhelm-zoccam** [comment] 2019-06-28 18:08
Still a problem in Gradle 5.4.1 w/Spotbugs 4.0.0-beta2.

**Comment by baev** [comment] 2020-04-03 16:55
the problem is that plugin adds `slf4-simple` dependency with fixed version `1.8.0-beta4` https://github.com/spotbugs/spotbugs-gradle-plugin/blob/master/build.gradle#L28 when Spring Boot uses dependency management plugin to import slf4 version from Spring Boot Parent pom (spring-boot-starter-parent) which is `1.7.30` (as for version 2.2.6.RELEASE). So the result classpath of spotbugs looks like this:

```
~/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.8.0-beta4/1531950ac50afd70a4d02f10b6aaf6d6a6a7669e/slf4j-simple-1.8.0-beta4.jar
~/.gradle/caches/modules-2/files-2.1/com.github.spotbugs/spotbugs/3.1.12/f44d1e64d96d683cc930622f1cc23b87a0bcd299/spotbugs-3.1.12.jar
~/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.30/b5a4b6d16ab13e34a88fae84c35cd5d68cac922c/slf4j-api-1.7.30.jar
~/.m2/repository/org/ow2/asm/asm-commons/7.0/asm-commons-7.0.jar
~/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-util/7.0/18d4d07010c24405129a6dbb0e92057f8779fb9d/asm-util-7.0.jar
~/.m2/repository/org/ow2/asm/asm-analysis/7.0/asm-analysis-7.0.jar
~/.m2/repository/org/ow2/asm/asm-tree/7.0/asm-tree-7.0.jar
~/.m2/repository/org/ow2/asm/asm/7.0/asm-7.0.jar
~/.gradle/caches/modules-2/files-2.1/org.apache.bcel/bcel/6.3/ab01e21304edb070aa840b856a4b26f17f901479/bcel-6.3.jar
~/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar
~/.m2/repository/org/dom4j/dom4j/2.1.1/dom4j-2.1.1.jar
~/.gradle/caches/modules-2/files-2.1/jaxen/jaxen/1.2.0/c10535a925bd35129a4329bc75065cc6b5293f2c/jaxen-1.2.0.jar
~/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
~/.gradle/caches/modules-2/files-2.1/com.github.spotbugs/spotbugs-annotations/3.1.12/ba2c77a05091820668987292f245f3b089387bfa/spotbugs-annotations-3.1.12.jar
~/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
```

`slf4j-simple-1.8.0-beta4.jar` is not compatible with `slf4j-api-1.7.30.jar` that causes warning. 

The possible workaround is to configure gradle dependency management plugin (https://plugins.gradle.org/plugin/io.spring.dependency-management) to use slf4j version `1.8.0-beta4` or manually override spotbugs classpath by using `afterEvaluate` hook for spotbugs gradle plugin:
 
```
afterEvaluate {
  val spotbugs = configurations.getByName("spotbugs")
  dependencies {
    spotbugs("org.slf4j:slf4j-nop:1.7.30") // or org.slf4j:slf4j-simple:1.7.30
    spotbugs("com.github.spotbugs:spotbugs:3.1.12")
  }
}
```

**Comment by KengoTODA** [comment] 2020-06-25 10:02
It is also possible to use `spotbugsSlf4j` configuration, then we can change the dependency for SLF4J provider:

```groovy
dependencies {
  spotbugsSlf4j  "org.slf4j:slf4j-simple:1.7.30"
}
```

**Comment by jscancella** [comment] 2021-03-29 14:17
@madorb is this still an issue?

**Comment by madorb** [comment] 2021-03-29 19:27
does not appear to be an issue anymore, no warnings using latest gradle

**Closed** 2021-09-08 01:30 UTC

**Comment by martmagi** [comment] 2021-12-20 08:59
FYI, this issue is back with Gradle `7.3.1`  and Spotbugs Gradle Plugin `5.0.3`. 

```
> Task :spotbugsMain
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

> Task :spotbugsTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by KengoTODA** [comment] 2021-12-20 10:16
@martmagi this repo itself meets the condition you pointed but no warning was reported.

https://github.com/spotbugs/spotbugs-gradle-plugin/runs/4544294283

Try to make a [mcve project](https://stackoverflow.com/help/minimal-reproducible-example), and create a new issue with it.
