### ISSUE TITLE
Deprecation warning wrt Gradle 9

### ISSUE THREAD

**Issue by Chessray** [spotbugs/spotbugs-gradle-plugin#895] opened 2023-05-16 14:06 UTC
Build output:

`The org.gradle.util.ConfigureUtil type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.1.1/userguide/upgrading_version_7.html#org_gradle_util_reports_deprecations
        at build_2my6sz9nofhu09ycuu5xrzoww$_run_closure2$_closure19$_closure26.doCall(/Users/raimundklein/development/GitHub/spring-boot-mvc-hexagonal-template/service/build.gradle:114)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
        at build_2my6sz9nofhu09ycuu5xrzoww$_run_closure2$_closure19.doCall(/Users/raimundklein/development/GitHub/spring-boot-mvc-hexagonal-template/service/build.gradle:113)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
`

Referenced section in the build file:

    spotbugsMain {
        reports {
            html {
                required = true
            }
        }
    }

**Comment by KengoTODA** [comment] 2023-05-19 01:29
Duplicate of #616

**Closed** 2023-10-08 01:46 UTC
