### ISSUE TITLE
toolVersion prints incorrectly

### ISSUE THREAD

**Issue by nibocn** [spotbugs/spotbugs-gradle-plugin#216] opened 2020-03-23 07:35 UTC
gradle version: 5.6.4
spotbugs plugin version: 4.0.x

code:

```
plugins {
    id 'java'
    id 'java-library'
    id 'idea'
    id 'eclipse'
//    id 'com.github.spotbugs' version '1.7.1' apply false
    id 'com.github.spotbugs' version '4.0.0'
//    id 'com.github.spotbugs' version '3.0.0'
}

spotbugs {
    includeFilter = file("$spotbugsDir/spotbugs-include-filter.xml")
    excludeFilter = file("$spotbugsDir/spotbugs-exclude-filter.xml")
    println "SpotBugs Version:${toolVersion}"
}
```

Show results:

```
SpotBugs Version:property(class java.lang.String, fixed(class java.lang.String, 4.0.0))
```

spotbugs plugin version: 3.0.0

results:

```
SpotBugs Version:3.1.12
```

**Comment by KengoTODA** [comment] 2020-04-15 00:00
This is intentional change: It is changed to [Property](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Property.html) that is officially recommended by Gradle.
Use methods in [Provider interface](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Provider.html) to get the actual value.

**Comment by KengoTODA** [comment] 2020-04-15 00:27
Duplicate of #215

**Closed** 2020-05-07 02:50 UTC
