### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by ati90ati** [spotbugs/spotbugs-gradle-plugin#133] opened 2019-03-17 15:33 UTC
Hello,

I have detected a problem in the plugin after upgraded to a newer version from 1.6.9.

> Task :spotbugsMain
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

This problem occurs in the version 1.6.10 / 1.6.11 / 1.7.0.
It happens on Java 8 and Java 11 also.
Gradle used: 5.2.1
As I observed it happens only if I have a project with Spring Boot (so this error will be present in each project which uses Spring Boot).
NOTE: Even the latest version of Spring Boot uses 1.7.x for the slf4j-api dependency.

Maybe this problem occurred after upgrading to slf4j-api version 1.8.0-beta-x

I've created a sample project to reproduce the problem:
https://github.com/ati90ati/bugreport-spotbugs-gradle-plugin-logging
You can run it with this command: `./gradlew clean build -PenableSpotbugs --warning-mode all`

I hope that this example helps to find a solution to the problem.

**Comment by noeliajimenezg** [comment] 2019-03-27 11:29
Hi,
I'm facing the same issue on version 1.7.1
I guess it could be related to this dependency problem https://www.mkyong.com/java/log4j2-failed-to-load-class-org-slf4j-impl-staticloggerbinder/

**Comment by rpalcolea** [comment] 2019-04-10 18:41
Looks like this was introduced on 1.6.10 -> https://github.com/spotbugs/spotbugs-gradle-plugin/blob/1.6.10/src/main/java/com/github/spotbugs/SpotBugsPlugin.java#L189 

Previously, no trace of sl4fj

**Comment by patrick-webs** [comment] 2019-10-09 22:03
This problem is also happening for me.

It appears to be some interaction between the spring boot gradle plugin and this plugin.

I tried adding slf4j-api and logback-classic to the classpath used by Spotbugs but it did not fix the issue, not sure why.

**Comment by sunzihao128858** [comment] 2019-10-12 12:42
add    "org.slf4j:slf4j-nop:1.7.25"  to  the  build.gradle

**Comment by MarcJose** [comment] 2019-10-12 12:55
I tried that before but it did not help.

**Comment by pineman** [comment] 2019-11-24 21:01
Still a problem. Can confirm it's something related to the spring boot plugin. Here's my `build.gradle` for reference:

```groovy
plugins {
	id 'application'
	id 'idea'
	id 'com.github.ben-manes.versions' version '0.27.0'
	id 'com.github.spotbugs' version '2.0.1'
	id 'pmd'

	id 'org.springframework.boot' version '2.2.1.RELEASE'
	id 'io.spring.dependency-management' version '1.0.8.RELEASE'
}

repositories {
	jcenter()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-dependencies:2.2.1.RELEASE'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
}

version = '0.1.0-SNAPSHOT'
application {
	mainClassName = 'foo'
}

pmd {
	ruleSets = ['java-quickstart']
}
spotbugs {
	toolVersion = '4.0.0-beta4'
}
```

Versions:
`javac 13.0.1`
```
------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13.0.1 (Oracle Corporation 13.0.1+9)
OS:           Mac OS X 10.14.5 x86_64
```

**Comment by adityasrini** [comment] 2019-12-03 04:23
I am getting this with micronaut 1.3.0.M1. I also have spring's dependency management plugin. I'm not sure if that could be a culprit here since others are having issues with their spring plugins (well spring boot) as well.

here's a portion of my `build.gradle`

```
plugins {
  id "com.github.spotbugs" version "3.0.0"
  id "com.github.johnrengelman.shadow" version "5.2.0"
  id "io.spring.dependency-management" version "1.0.8.RELEASE"
  id "org.flywaydb.flyway" version "6.1.0"
}

ext {
  micronautVersion = '1.3.0.M1'
}

version "1"
group "homeless-services-directory"

apply plugin: "application"
apply plugin: "java"
apply plugin: 'jacoco'

repositories {
  mavenLocal()
  mavenCentral()
  jcenter()
  maven { url "https://oss.jfrog.org/oss-snapshot-local" }
}

dependencyManagement {
  imports {
    mavenBom "io.micronaut:micronaut-bom:$micronautVersion"
  }
}

dependencies {
  annotationProcessor "io.micronaut:micronaut-inject-java"
  annotationProcessor "io.micronaut:micronaut-security"

  compileOnly "io.micronaut:micronaut-inject-java"
  compile "io.micronaut:micronaut-http-client"
  compile "io.micronaut:micronaut-http-server-netty"
  compile "io.micronaut:micronaut-inject"
  compile "io.micronaut:micronaut-runtime"
  compile "io.micronaut.configuration:micronaut-jdbc-hikari"
  compile "javax.annotation:javax.annotation-api:1.3.2"
  compile 'org.springframework:spring-jdbc:5.0.9.RELEASE'

  // view
  compile 'io.micronaut:micronaut-views'
  runtime 'org.thymeleaf:thymeleaf:3.0.11.RELEASE'

  // security
  compile "io.micronaut:micronaut-security"
  compile 'io.micronaut.configuration:micronaut-security-oauth2'
  compile 'io.micronaut:micronaut-security-jwt'
  compile 'io.micronaut:micronaut-session'
  compile 'io.micronaut:micronaut-security-session'

  testAnnotationProcessor "io.micronaut:micronaut-inject-java"
  testCompile "io.micronaut.test:micronaut-test-junit5"
  testCompile "io.micronaut.test:micronaut-test-spock"
  testCompile 'org.junit.jupiter:junit-jupiter-api:5.3.2'
  testCompile 'org.junit.jupiter:junit-jupiter-params:5.3.2'
  testCompile 'org.skyscreamer:jsonassert:1.5.0'
  testRuntime 'org.junit.jupiter:junit-jupiter-engine:5.3.2'

  runtime "ch.qos.logback:logback-classic:1.2.3"
  runtime 'org.postgresql:postgresql:42.2.5'
}

shadowJar {
  mergeServiceFiles()
}
```

**Comment by kastork** [comment] 2020-03-18 15:30
I've produced the problem with a brand-new 1.3.3 project.

`./gradlew dependencies` shows a lot of transitive dependencies that are being resolved to a beta version of slf4j.  Maybe this is actually a gradle issue?

```
+--- io.micronaut:micronaut-bom:1.3.3
|    +--- io.micronaut:micronaut-runtime:1.3.3 (c)
|    +--- io.micronaut.aws:micronaut-function-aws-api-proxy:1.3.9 (c)
|    +--- io.micronaut.aws:micronaut-function-aws-custom-runtime:1.3.9 (c)
|    +--- org.slf4j:slf4j-api:1.7.26 -> 1.8.0-beta2 (c)
```

**Comment by KengoTODA** [comment] 2020-03-18 17:12
Please try the latest version 4.0.x instead of 3.0.0.

**Comment by daggerok** [comment] 2020-03-23 21:33
we cannot use > 2.0.0, how to fix that problem with gradle plugin 2.0.0?

**Comment by KengoTODA** [comment] 2020-06-25 10:03
Duplicate of #136

**Comment by KengoTODA** [comment] 2020-06-25 11:56
I'll close this duplicated issue. use #136 instead.

**Closed by KengoTODA** 2020-06-25 11:56 UTC

**Comment by eceeb** [comment] 2023-09-26 11:49
still the same problem here
